#!/usr/bin/env bash
# Onion Classifieds — unattended .env generator.
#
# Produces a COMPLETE .env for the full self-hosted Supabase stack + the PHP
# app: random secrets, and correctly-signed HS256 JWTs for ANON_KEY /
# SERVICE_ROLE_KEY (derived from JWT_SECRET). Idempotent: if .env already
# exists it is left untouched unless --force is passed. Requires only bash +
# openssl (no Node, no Supabase CLI) so it runs from cloud-init with nothing
# pre-installed but coreutils.
set -euo pipefail
cd "$(dirname "$0")/.."

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

if [ -f .env ] && [ "$FORCE" -ne 1 ]; then
  echo "✅ .env already exists — leaving it (use --force to regenerate)."
  exit 0
fi

rand_hex()  { openssl rand -hex "${1:-32}"; }
# url-safe base64 with padding stripped
b64url() { openssl base64 -e -A | tr '+/' '-_' | tr -d '='; }

# Mint an HS256 JWT for a Supabase role, signed with JWT_SECRET.
jwt() {
  local role="$1" secret="$2" iat exp header payload sig
  iat=$(date +%s)
  exp=$((iat + 3650 * 24 * 3600)) # ~10 years
  header=$(printf '{"alg":"HS256","typ":"JWT"}' | b64url)
  payload=$(printf '{"role":"%s","iss":"supabase","iat":%s,"exp":%s}' "$role" "$iat" "$exp" | b64url)
  sig=$(printf '%s' "$header.$payload" | openssl dgst -sha256 -hmac "$secret" -binary | b64url)
  printf '%s.%s.%s' "$header" "$payload" "$sig"
}

echo "🔐 Generating secrets + Supabase JWT keys…"
POSTGRES_PASSWORD="$(rand_hex 24)"
JWT_SECRET="$(openssl rand -base64 48 | tr -d '=+/' | cut -c1-48)"
APP_SECRET="$(rand_hex 32)"
DASHBOARD_USERNAME="admin"
DASHBOARD_PASSWORD="$(rand_hex 12)"
LOGFLARE_API_KEY="$(rand_hex 32)"
ANON_KEY="$(jwt anon "$JWT_SECRET")"
SERVICE_ROLE_KEY="$(jwt service_role "$JWT_SECRET")"

# Public URL: the .onion (set later by get-onion-address.sh) or a placeholder.
APP_BASE_URL="${APP_BASE_URL:-http://localhost:8080}"

cat > .env <<EOF
# ── GENERATED by scripts/generate-env.sh — do not commit ──────────────────
# Regenerate with: ./scripts/generate-env.sh --force

############ Postgres / Supabase core ############
POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=3600
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

############ Supabase Studio / Kong ############
DASHBOARD_USERNAME=${DASHBOARD_USERNAME}
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
STUDIO_DEFAULT_ORGANIZATION="Onion Classifieds"
STUDIO_DEFAULT_PROJECT=OnionClassifieds
STUDIO_PORT=3000
KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443
SUPABASE_PUBLIC_URL=http://localhost:8000
API_EXTERNAL_URL=http://localhost:8000
SITE_URL=${APP_BASE_URL}
ADDITIONAL_REDIRECT_URLS=
PGRST_DB_SCHEMAS=public,storage,graphql_public
LOGFLARE_API_KEY=${LOGFLARE_API_KEY}
FUNCTIONS_VERIFY_JWT=false
IMGPROXY_ENABLE_WEBP_DETECTION=true
DOCKER_SOCKET_LOCATION=/var/run/docker.sock

############ GoTrue (auth) — anonymous-account app, email/phone off ############
DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=false
ENABLE_ANONYMOUS_USERS=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false
SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=supabase-mail
SMTP_PORT=2500
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME="Onion Classifieds"
MAILER_URLPATHS_INVITE=/auth/v1/verify
MAILER_URLPATHS_CONFIRMATION=/auth/v1/verify
MAILER_URLPATHS_RECOVERY=/auth/v1/verify
MAILER_URLPATHS_EMAIL_CHANGE=/auth/v1/verify

############ PHP application ############
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
APP_SECRET=${APP_SECRET}
APP_BASE_URL=${APP_BASE_URL}
APP_DEBUG=false

# Exchange rates (Tatum) — REQUIRED for pricing; set your key before going live.
TATUM_API_URL=https://api.tatum.io/v3
TATUM_API_KEY=your-tatum-api-key

# CryptAPI payout addresses — REQUIRED; replace with your own before going live.
PAYOUT_BTC=your-btc-address
PAYOUT_XMR=your-xmr-address
PAYOUT_ETH=your-eth-address
PAYOUT_SOL=your-sol-address
PAYOUT_DOGE=your-doge-address
PAY_CONF_DEFAULT=1
PAY_CONF_BTC=1
PAY_CONF_XMR=10
PAY_CONF_ETH=12
PAY_CONF_SOL=1
PAY_CONF_DOGE=6

# Pricing (USD cents)
LISTING_PRICE_CENTS=100
BUMP_PRICE_CENTS=50

# Uploads / sessions / rate limiting
UPLOAD_MAX_SIZE=15242880
UPLOAD_MAX_FILES=5
UPLOAD_ALLOWED_TYPES=image/jpeg,image/png,image/webp
SESSION_LIFETIME=86400
CSRF_TOKEN_LIFETIME=3600
RATE_LIMIT_ENABLED=true
RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW=3600
EOF

chmod 600 .env
echo "✅ Wrote complete .env (Postgres pw, JWT secret, ANON/SERVICE JWTs, dashboard creds)."
echo "   Dashboard: ${DASHBOARD_USERNAME} / ${DASHBOARD_PASSWORD}"
echo "   ⚠  Set TATUM_API_KEY and PAYOUT_* before accepting real payments."
